<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.ontimize.labs</groupId>
		<artifactId>ontimize-core-parent</artifactId>
		<version>7.0.0-SNAPSHOT</version>
	</parent>
	<artifactId>ontimize-jee-report</artifactId>
	<packaging>pom</packaging>
	
	<properties>
		<jasperreports.version>6.2.0</jasperreports.version>
		<jasperreports.fonts.version>6.0.0</jasperreports.fonts.version>
	</properties>
	
	<dependencyManagement>
		<dependencies>
		
			<dependency>
				<groupId>net.sf.jasperreports</groupId>
				<artifactId>jasperreports</artifactId>
				<version>${jasperreports.version}</version>
				<exclusions>
					<exclusion>
						<artifactId>commons-logging</artifactId>
						<groupId>commons-logging</groupId>
					</exclusion>
					<exclusion>
						<artifactId>olap4j</artifactId>
						<groupId>org.olap4j</groupId>
					</exclusion>
					<exclusion>
						<groupId>eclipse</groupId>
						<artifactId>jdtcore</artifactId>
					</exclusion>
					<exclusion>
						<groupId>com.fasterxml.jackson.core</groupId>
						<artifactId>jackson-core</artifactId>
					</exclusion>
					<exclusion>
						<groupId>com.fasterxml.jackson.core</groupId>
						<artifactId>jackson-databind</artifactId>
					</exclusion>
					<exclusion>
						<groupId>com.fasterxml.jackson.core</groupId>
						<artifactId>jackson-annotations</artifactId>
					</exclusion>
					<exclusion>
						<groupId>bouncycastle</groupId>
						<artifactId>bcmail-jdk14</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.bouncycastle</groupId>
						<artifactId>bcprov-jdk14</artifactId>
					</exclusion>
					<exclusion>
						<groupId>bouncycastle</groupId>
						<artifactId>bcprov-jdk14</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.bouncycastle</groupId>
						<artifactId>bctsp-jdk14</artifactId>
					</exclusion>
					<exclusion>
						<groupId>xml-apis</groupId>
						<artifactId>xml-apis</artifactId>
					</exclusion>
					<exclusion>
						<groupId>javax.xml.stream</groupId>
						<artifactId>stax-api</artifactId>
					</exclusion>
					<exclusion>
						<groupId>stax</groupId>
						<artifactId>stax</artifactId>
					</exclusion>
					<exclusion>
						<groupId>jakarta-regexp</groupId>
						<artifactId>jakarta-regexp</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>net.sf.jasperreports</groupId>
				<artifactId>jasperreports-fonts</artifactId>
				<version>${jasperreports.fonts.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	
	<modules>
		<module>ontimize-jee-report-common</module>
		<module>ontimize-jee-report-server</module>
	</modules>
</project>