name: Generate a SNAPSHOT in Artifactory
on: workflow_dispatch
jobs:
  Generate-a-SNAPSHOT-in-Artifactory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Setup Java JDK and Maven
        uses: ontimize/setup-java-maven-gitAction@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Perform MVN actions
        run: |
          java -version
          mvn -v
          mvn help:effective-settings