name: Prepare a release by a pull request
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Optional. Enter a new custom version instead of default existing one'
        type: string
        required: false
jobs:
  Prepare-a-release-by-a-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Get framework version to release
        id: version
        run: |
          var_version=$(mvn help:evaluate -q -Dexpression=project.version -DforceStdout)
          echo "Version release: $var_version" 
          if  ${{ github.event.inputs.version != '' }} ; then
            var_version=${{ github.event.inputs.version }}
          else
            var_version=$(mvn help:evaluate -q -Dexpression=project.version -DforceStdout) 
          fi
          
          echo "Version release: $var_version"
          echo "version=$var_version" >> $GITHUB_OUTPUT
      - name: Check passing value
        run: |
          echo ${{ steps.version.outputs.version }}